[build]
  base = "/"
  command = "yarn build"
  publish = "build"

[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = [
      "node_modules/.cache",
    ]

[[redirects]]
  from = "/getstarted"
  to = "/get-questdb/"

[[redirects]]
  from = "/get-started"
  to = "/get-questdb/"

[[redirects]]
  from = "/docs/reference/web-console"
  to = "/docs/develop/web-console/"

[[redirects]]
  from = "/docs/develop/authenticate"
  to = "/docs/reference/api/ilp/authenticate/"

[[redirects]]
  from = "/docs/reference/client/grafana"
  to = "/docs/third-party-tools/grafana/"

[[redirects]]
  from = "/docs/guides/aws-official-ami"
  to = "/docs/deployment/aws-official-ami/"

[[redirects]]
  from = "/docs/guides/digitalocean"
  to = "/docs/deployment/digitalocean/"

[[redirects]]
  from = "/docs/guides/google-cloud-platform"
  to = "/docs/deployment/google-cloud-platform/"

[[redirects]]
  from = "/docs/guides/kubernetes"
  to = "/docs/deployment/kubernetes/"

[[redirects]]
  from = "/blog/2020/12/10/building-a-garbage-free-network-stack-for-kafka-streams"
  to = "/blog/2020/12/10/garbage-free-stack-for-kafka-streams/"

[[redirects]]
  from = "/blog/2020/12/10/non-blocking-io-without-garbage-collection"
  to = "/blog/2020/12/10/garbage-free-stack-for-kafka-streams/"

[[redirects]]
  from = "/blog/2020/12/10/building-a-garbage-free-network-stack-for-kafka-streams"
  to = "/blog/2020/12/10/non-blocking-io-without-garbage-collection/"

[[redirects]]
  from = "/tutorial/2020/10/19/grafana"
  to = "/blog/2020/10/19/grafana-tutorial/"

[[redirects]]
  from = "/tutorial/2020/06/05/iot-on-questdb"
  to = "/blog/2020/06/05/iot-on-questdb/"

[[redirects]]
  from = "/tutorial/2020/06/15/python-questdb-tutorial"
  to = "/blog/2020/06/15/python-questdb-tutorial/"

[[redirects]]
  from = "/tutorial/2020/07/22/influxdb-lp-on-tcp"
  to = "/blog/2020/07/22/influxdb-lp-on-tcp/"

[[redirects]]
  from = "/tutorial/2020/08/25/questitto"
  to = "/blog/2020/08/25/fast-iot-stack-with-questdb-mqtt/"

[[redirects]]
  from = "/blog/2020/11/26/http-server-contribution"
  to = "/blog/2020/11/16/http-server-contribution/"

[[redirects]]
  from = "/blog/2020/11/16/why-timeseries-data"
  to = "/blog/2020/11/26/why-timeseries-data/"

[[redirects]]
  from = "/blog/2020/03/15/interthread"
  to = "/blog/2021/11/03/interthread/"

[[redirects]]
  from = "/tutorial/2021/01/13/application-uptime-monitoring-with-python-nuxtjs-questdb"
  to = "/blog/2021/01/13/application-uptime-monitoring-with-python-nuxtjs-questdb/"

[[redirects]]
  from = "/tutorial/2021/01/18/low-code-bitcoin-ticker-workflow-with-time-series-database"
  to = "/blog/2021/01/18/low-code-bitcoin-ticker-workflow-with-time-series-database/"

[[redirects]]
  from = "/tutorial/2021/02/05/streaming-heart-rate-data-with-iot-core-and-questdb"
  to = "/blog/2021/02/05/streaming-heart-rate-data-with-iot-core-and-questdb/"

[[redirects]]
  from = "/tutorial/2021/02/18/realtime-crypto-tracker-with-kafka-and-questdb"
  to = "/blog/2021/02/18/realtime-crypto-tracker-with-kafka-and-questdb/"

[[redirects]]
  from = "/tutorial/2021/03/09/realtime-stock-alerts-python-grafana-questdb"
  to = "/blog/2021/03/09/realtime-stock-alerts-python-grafana-questdb/"

[[redirects]]
  from = "/tutorial/2021/03/18/questdb-and-prometheus-on-gke-autopilot"
  to = "/blog/2021/03/18/questdb-and-prometheus-on-gke-autopilot/"

[[redirects]]
  from = "/tutorial/2021/03/31/automating-etl-jobs-on-time-series-data-on-gcp"
  to = "/blog/2021/03/31/automating-etl-jobs-on-time-series-data-on-gcp/"

[[redirects]]
  from = "/tutorial/2021/04/12/ethereum"
  to = "/blog/2021/04/12/stream-ethereum-data/"

[[redirects]]
  from = "/tutorial/2021/06/18/tracking-multiple-cryptocurrency-exchanges"
  to = "/blog/2021/06/18/tracking-multiple-cryptocurrency-exchanges/"

[[redirects]]
  from = "/tutorial/2021/07/09/telegraf-and-questdb-for-storing-metrics-in-a-timeseries-database"
  to = "/blog/2021/07/09/telegraf-and-questdb-for-storing-metrics-in-a-timeseries-database/"

[[redirects]]
  from = "/tutorial/2021/07/05/comparing-questdb-timescaledb-influxdb/"
  to = "/blog/2021/07/05/comparing-questdb-timescaledb-influxdb/"

[[redirects]]
  from = "/tutorial/2021/08/18/questdb-versus-timescaledb"
  to = "/blog/2021/08/18/questdb-versus-timescaledb/"

[[redirects]]
  from = "/tutorial/2021/09/17/high-frequency-finance-julia-lang"
  to = "/blog/2021/09/17/high-frequency-finance-julia-lang/"

[[redirects]]
  from = "/tutorial/2021/11/01/plotly-finnhub-realtime-dashboard"
  to = "/blog/2021/11/01/plotly-finnhub-realtime-dashboard/"

[[redirects]]
  from = "/tutorial/2021/11/29/questdb-versus-influxdb"
  to = "/blog/2021/11/29/questdb-versus-influxdb/"

[[redirects]]
  from = "/tutorial/2021/11/22/high-frequency-finance-introduction-julia-lang"
  to = "/blog/2021/11/22/high-frequency-finance-introduction-julia-lang/"

[[redirects]]
  from = "/tutorial/2022/02/10/questdb-google-data-studio/"
  to = "/blog/2022/02/10/questdb-google-data-studio/"

[[redirects]]
  from = "/tutorial/2022/03/08/questdb-crypto-pandas/"
  to = "/blog/2022/03/08/questdb-crypto-pandas/"

[[redirects]]
  from = "/tutorial/2022/03/14/mock-sql-timeseries-data-questdb/"
  to = "/blog/2022/03/14/mock-sql-timeseries-data-questdb/"

[[redirects]]
  from = "/tutorial/2022/03/15/cryptocurrency-grafana-questdb/"
  to = "/blog/2022/03/15/cryptocurrency-grafana-questdb/"

[[redirects]]
  from = "/tutorial/2022/03/29/crypto-volumes-julia-questdb/"
  to = "/blog/2022/03/29/crypto-volumes-julia-questdb/"

[[redirects]]
  from = "/docs/reference/client/cli"
  to = "/docs/reference/command-line-options/"

[[redirects]]
  from = "/docs/reference/client/web-console"
  to = "/docs/reference/web-console/"

[[redirects]]
  from = "/docs/guides/hysteresis"
  to = "/docs/guides/out-of-order-commit-lag/"

[[redirects]]
  from = "/tutorial/2021/09/05/telegraf-and-questdb-for-storing-metrics-in-a-timeseries-database"
  to = "/blog/2021/07/09/telegraf-and-questdb-for-storing-metrics-in-a-timeseries-database/"

[[redirects]]
  from = "/blog/2021/09/13/release-6-0-5"
  to = "/blog/2021/09/13/release-6-0-5-geospatial-data/"

[[redirects]]
  from = "/blog/2021/07/16/release-6-0-4"
  to = "/blog/2021/07/16/release-6-0-4-prometheus-metrics/"

[[redirects]]
  from = "/careers/head-of-talent/"
  to = "/careers/people-and-talent-acquisition/"

[[redirects]]
  from = "/careers/backend-software-engineer/"
  to = "/careers/core-database-engineer/"

[[redirects]]
  from = "/case-study/innova/"
  to = "/case-study/turk-telekom/"

[[redirects]]
  from = "/developer-in-test"
  to = "/careers/"

[[redirects]]
  from = "/people-and-talent-acquisition"
  to = "/careers/"

[[redirects]]
  from = "/docs/reference/sql/latest-by"
  to = "/docs/reference/sql/latest-on/"

[[redirects]]
  from = "/docs/reference/api/influxdb"
  to = "/docs/reference/api/ilp/overview/"

[[redirects]]
  from = "/docs/guides/influxdb-line-protocol"
  to = "/docs/reference/api/ilp/overview/"

[[redirects]]
  from = "/docs/faq/troubleshooting"
  to = "/docs/troubleshooting/faq/"

[[redirects]]
  from = "/blog/2022/05/26/multi-threaded-sql-filters"
  to = "/blog/2022/05/26/query-benchmark-questdb-versus-clickhouse-timescale/"

[[redirects]]
  from = "/docs/guides/aws-packer"
  to = "/docs/deployment/aws-official-ami/"

[[redirects]]
  from = "/docs/operations/deployment"
  to = "/docs/deployment/aws-official-ami/"

[[redirects]]
  from = "/docs/introduction"
  to = "/docs/"

[[redirects]]
  from = "/blog/2022/04/12/query-live-crypto-trades-with-sql-in-real-time"
  to = "/blog/2022/04/12/demo-live-crypto-data-streamed-with-questdb-and-grafana/"

[[redirects]]
  from = "/docs/reference/ilp-client-libraries"
  to = "/docs/reference/clients/overview/"

[[redirects]]
  from = "/tutorial"
  to = "/blog/tags/tutorial/"

[[redirects]]
  from = "/blog/2022/09/12/importing-3m-rows-with-io-uring"
  to = "/blog/2022/09/12/importing-300k-rows-with-io-uring/"

[[redirects]]
  from = "/docs/reference/sql/except-intersect"
  to = "/docs/reference/sql/union-except-intersect/"

[[redirects]]
  from = "/docs/reference/sql/timestamp"
  to = "/docs/reference/function/timestamp/"

[[redirects]]
  from = "/docs/third-party-tools/kafka/"
  to = "/docs/third-party-tools/kafka/overview/"

[[redirects]]
  from = "/blog/2020/11/26/why-timeseries-data/"
  to = "/blog/time-series-data/"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "frame-src 'self' app.netlify.com calendly.com *.questdb.io www.youtube.com www.slideshare.net;"
