let guidelines

if (process.env.NODE_ENV === "development") {
  guidelines = {
    label: "Guidelines (DEV ONLY)",
    type: "category",
    items: [
      {
        type: "category",
        label: "Templates",
        items: [
          "__guidelines/template/guide",
          "__guidelines/template/function",
          "__guidelines/template/sql",
        ],
      },
      "__guidelines/naming-convention",
      "__guidelines/content-hierarchy",
      "__guidelines/lexicon",
      "__guidelines/markdown",
      "__guidelines/sql-code-blocks",
      "__guidelines/influences",
    ],
  }
}

module.exports = {
  docs: [
    // {
    //   type: 'autogenerated',
    //   dirName: '.', // '.' 即当前的文档文件夹
    // },
    // {
    //   id: "介绍",
    //   type: "doc",
    // },
//     - [Web在线练习](/docs/get-started/docker/) Web在线练习
// - [Mac跟打练习](/docs/get-started/binaries/) Mac跟打练习
// - [Web程序与Mac程序的区别](/docs/get-started/homebrew/) Web程序与Mac程序的区别
// - [Learn more](/docs/get-started/learn-more/) is a selection of useful concepts
    {
      id: "introduction",
      type: "doc",
    },
    {
      label: "快速开始",
      type: "category",
      items: [
        {
          label: "Web在线练习",
          type: "link",
          href: "https://typer.owenyang.top/",
        },
        {
          label: "Mac跟打练习",
          type: "link",
          href: "https://typer.owenyang.top/",
        },
        {
          label: "Web程序与Mac程序的区别",
          type: "link",
          href: "https://typer.owenyang.top/",
        },
        {
          label: "常用设置",
          type: "link",
          href: "https://typer.owenyang.top/",
        },
      ],
    },
    {
      label: "使用指南",
      type: "category",
      items: [
        {
          label: "易跟打macOS版下载",
          id: "guides/download",
          type: "doc",
        },
      ],
    },
    {
      id: "changelog",
      type: "doc",
    },
    // guidelines,
  ].filter(Boolean),
}
